### ISSUE TITLE
Add pyblish tray functionality

### ISSUE THREAD

**Issue by BigRoy** [pyblish/pyblish-shell#5]
### Goal

To add a `pyblish-tray` executable so one can launch the tray functionality similar to running `pyblish_qml.exe`. This as an artist-friendly way of keeping pyblish qml running the background whilst being able to manage it using the tray icon.
### Motivation

Currently the process can only be found in the task manager and for an artist it is unclear whether the process is currently running (`pyblish_qml.exe`) without looking there, especially if the process was run without an open console to debug.

Having the tray accessible to check the logs for debugging and seeing it active there is a first step to really get `pyblish-tray` into the mainstream.

_Based on [reply on the forums](http://forums.pyblish.com/t/pyblish-and-pyblish-win-renovation/214/12?u=bigroy)_

Note: It would be great if this would by default start [without an additional console window](http://forums.pyblish.com/t/pyblish-and-pyblish-win-renovation/214/11?u=bigroy) since the tray interface itself acts as debugging console.

**Comment by mottosso** [comment]
Note to implementer;

We'll need to implement the `-u` flag, or "unbuffered mode", for the underlying Python process as Pyblish Tray relies on this ability to properly retrieve the output from the child Pyblish QML process.
- [pyblish_shell.py:-u](https://github.com/pyblish/pyblish-shell/blob/fa317123fcfe37e20ba084432dade41a8dce1222/pyblish_shell.py#L32)

**Comment by mottosso** [comment]
Initially, I was thinking pyblish-tray could use the Windows-based `pythonw` rather than `python` for a native GUI application. But the problem is that GUI applications on Windows can't take command line arguments, and we need those.

So instead, I'll bundle an optional `.bat` script for Windows users to run without a console.

**Comment by BigRoy** [comment]
Sounds fine with me. Thanks for pointing that out!

**Comment by mottosso** [comment]
This has been implemented in 1.1.
- https://github.com/pyblish/pyblish-shell/releases
